# Generated by Django 5.1.5 on 2025-09-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_list_db',
            name='Genre',
            field=models.CharField(choices=[('0', 'Action'), ('1', 'Crime'), ('2', 'Comedy'), ('3', 'Drama'), ('4', 'Adventure'), ('5', 'Romance'), ('6', 'Sci-Fi')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='genre_db',
            name='genre_name',
            field=models.CharField(choices=[('0', 'Action'), ('1', 'Crime'), ('2', 'Comedy'), ('3', 'Drama'), ('4', 'Adventure'), ('5', 'Romance'), ('6', 'Sci-Fi')], max_length=30),
        ),
    ]
