# Generated by Django 5.1.5 on 2025-09-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0002_movies_list_db_genre_alter_genre_db_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies_list_db',
            name='genre',
        ),
    ]
