# Generated by Django 5.1.5 on 2025-09-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0003_remove_movies_list_db_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies_list_db',
            name='Genre',
        ),
        migrations.AddField(
            model_name='movies_list_db',
            name='genre',
            field=models.ManyToManyField(to='Movies_House.genre_db'),
        ),
    ]
