# Generated by Django 5.1.5 on 2025-09-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0008_alter_seats_left_seats_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='seats_left',
            name='seats_left',
        ),
        migrations.AddField(
            model_name='seats_left',
            name='seats_left',
            field=models.ManyToManyField(to='Movies_House.seat'),
        ),
    ]
