# Generated by Django 5.1.5 on 2025-09-17 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0009_seat_remove_seats_left_seats_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats_left',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_seats', to='Movies_House.movies_list_db'),
        ),
    ]
