# Generated by Django 5.1.5 on 2025-09-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0010_alter_seats_left_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat',
            field=models.CharField(max_length=5),
        ),
    ]
