# Generated by Django 5.1.5 on 2025-09-18 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0011_alter_seat_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats_left',
            name='seats_left',
        ),
        migrations.RemoveField(
            model_name='seats_left',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seats_left',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='playdates',
            unique_together={('movie', 'date')},
        ),
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=2)),
                ('row', models.PositiveBigIntegerField()),
            ],
            options={
                'unique_together': {('col', 'row')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Movies_House.playdates')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies_House.movies_list_db')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies_House.seatmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_booked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'seat')},
            },
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Seats_left',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
