# Generated by Django 5.1.5 on 2025-09-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0012_remove_seats_left_seats_left_remove_seats_left_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmodel',
            name='col',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=2),
        ),
        migrations.AlterField(
            model_name='seatmodel',
            name='row',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
    ]
