# Generated by Django 5.1.5 on 2025-09-19 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0013_alter_seatmodel_col_alter_seatmodel_row'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('date', 'seat_row', 'seat_col')},
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_col',
            field=models.ForeignKey(default='A', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_col', to='Movies_House.seatmodel'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_row',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_row', to='Movies_House.seatmodel'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
    ]
