# Generated by Django 5.1.5 on 2025-09-19 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0014_alter_ticket_unique_together_ticket_seat_col_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('date', 'seat')},
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(default='A1', on_delete=django.db.models.deletion.CASCADE, to='Movies_House.seatmodel'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_col',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_row',
        ),
    ]
