# Generated by Django 5.1.5 on 2025-09-19 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0015_alter_ticket_unique_together_ticket_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(default='A2', on_delete=django.db.models.deletion.CASCADE, to='Movies_House.seatmodel'),
        ),
    ]
