# Generated by Django 5.1.5 on 2025-09-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_House', '0016_alter_ticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies_list_db',
            name='tickets_left',
        ),
        migrations.AddField(
            model_name='playdates',
            name='tickets_left',
            field=models.IntegerField(default=100),
        ),
    ]
